POST http://localhost:8000/api/user/oten HTTP/1.1
Content-Type: application/json 

{

     "name" : "Jeremy Andy F. Ampatin",
     "birthdate" :"October 04, 2001",
     "email": "jeremyandyampatin@gmail.com",
     "username": "ampatin123",
     "password" : "09153569802"
}

